language: r
dist: trusty
sudo: false
notifications:
  email: false
branches:
  only: master
addons:
  ssh_known_hosts: credibleinterval.ee
cache:
  packages: true
  directories:
  - $HOME/bin
before_install:
- sudo apt-get update -q
- sudo apt-get install libimage-exiftool-perl -y
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
before_deploy:
- openssl aes-256-cbc -K $encrypted_288f77d8e810_key -iv $encrypted_288f77d8e810_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/ virt64551@credibleinterval.ee:~/domeenid/www.credibleinterval.ee/htdocs
  on:
    branch: master
