language: r
dist: trusty
sudo: false
notifications:
  email: false
branches:
  only: master
addons:
  ssh_known_hosts: credibleinterval.ee
cache:
  packages: true
  directories:
  - $HOME/bin
before_install:
- sudo apt-get update -q
- sudo apt-get install libimage-exiftool-perl -y
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
before_deploy:
- openssl aes-256-cbc -K $encrypted_288f77d8e810_key -iv $encrypted_288f77d8e810_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
- chmod +x ./deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: UVdWahaL1tHPK/Gkum7JNFMb2acmAwlHWC5aIvno/VqH9OkJsNRieJSV6yACpUcylujoWb/F4BQtZFmOipGE8STzytOhm5mEF332vCNdER3yFnAT2JkH4CMYXU52jEGTQz8C21vT/A/+WQCZk4PHeTtGJNeJg+tQzGTV7u0UrLY3IQmCY95VIat596C+vTyhkEe58ALrBryO8Mucn/P5hvfzZol4/NOaw8TXXIXFiI5lJBeR2OnxJMUOeADy1hKbRm2bsOdbnXJEvtzw2pPEQN5MzkcZr5tOdRuQ24WtC8IjQUd2rlZBpED3hvJH6mj7ufmAKK82qEVk3f3C6P9F0Llxsidve9RKNmMxBQJfjca8jAghCJlNUND85TziR8b5FSvjgS8bry056gEO98vK89/A4mCI39Kh+Sl283fMS3+4RzHhUUdLdoKXC26r4+HeftRei4IcRpD2RgbSoTmwtTKA+mxtvVaY+F9BVBYDxIg2j2ihUn3uGPbmMC0XObQenFVPBJVj6NP35MO5qRDLGoCfyevp3p/H9ok82cEK2fmsJaRtoVEmCN5vE2WW8ih62KX0Ri5/G3pzFq6DMPuwYC119sbFYjRx+GFRkLbrP68P59cM/33KdoSvUDWoQU/EDbLDxks/7l1i4cUELx0UTuzG8dPOhSKzfd+HM7cF2z0=
  - secure: sZ2WlDp7IelCkFW1Gkwj8RHJbLLvUMU9WXe3x9VLLVQiEBCliVh/wzlpjk1/ys1iF1MoC+sYciyeY35ge4MCf+g5kILS/+e/+d3+0+umyy+PQGprtaKQaDkntJ7cZkhQm6J7MF4zzbjQk1MpzUZ/zOlQADIT6LA8Vsh+pdzvqdKHqr+jijOKLhwd2k3tfZF80+CSJuYMnaU2XhVNKbwYXxPt/h7Mtznz5eAkY5HtgoC6Rlc9KZX5NhNm+3/pgq0gh2nDc1E5PLCrfGZRMOMOq/Up36XUYKFbwYL4Pwa0X3+4OnLhwKtr4HIIvAYbFCaZStuy1Hc1T/p1myq1zbqW3BO3UIHaAhlZoZmgi6vsb33rjsK4qZrpOzFC8SIKgDyrbya4QKWYc82/qjCfneVsHvXGro8ypjssDNxh9ff2tyk0rtQ2FjR7rrbBNBkW2987Vx6KI34k+IZiPweFvrwVbzo0ph/vh5/Hqwj2JBPC+gIxZASnJzdILr9PKe+hYMEzSq/llwc6ki/GhM9IYTIZ9osJ+fgiC0YinnPFvY/+hmW34pXI1PQ+/BhlqnVPtmNocYYrxTmaXOPgWOoH3FsQzW07N2ExRkhzFDa0tTyjr+VEsJcJhJ8nJIme3i2p1/3ylMPWbiAXnOLMlWKSoXpaIowzPFubZUyDynQ4yz5sGGo=
  - secure: t8TCYRMGh4u4dw5llBUxwXao0IcvJqE58iL40TN2jN7zIFp55e5uC0yITrewRqRbqaEdr/qOOgM5pKtkwKjkka1ym1HY0seMeheqOiqqIAwp2c9iWlLNlxayikQgXanHkA4EAz2D4uGvcJGAFn1bjgb/LU1oHhQWINvGLWidRlMxYMb1gbWIRri5VMfIMbXy4a6JQEig5DfNsf83CatB6zMXTyUdXfmwvlw0HjB8fByToqvkhFNG2i3Lhb18RmobRVAyiqTEWWb2yyOrXnZrqGAUsCNhcsQkmtBuURy4lPMH1Q/PdfvT7eEZdURi/GiBJyXcB2JzTlbolKC0gq8XbFYvg1idZs7maXU8uIRlGhakXtjZnxq7cPHWL/LnanqFWo32WDz8zHln8n2Lo0HnT1LYHGA0VAlS/VsDoC5HpLnYKP1ZKZmGO9gNnjksPrT73Qt3rC+goOCD8UfakJmtpZwfSoCF3GDZcoy8kwDAvdlJI/u5kKLIPYZnvr3/cjD6HmixyLCOPYvssawLZ2UB+3P8zy605stvZaGoYDXnsoCerXVUzNeUt/qxMKnqxMUDBYUz1yHK41mziNPuJSTYRfBHdl/Yq9LZv6YATEWfKTBjB1vvzJ4Uan7HQfIsONQO4gw+BGcFY0Wi0fJh+cJXI4VH2KEpF+kwO5K6WraQtVk=
