language: r
dist: trusty
sudo: false
notifications:
  email: false
branches:
  only: master
addons:
  ssh_known_hosts: credibleinterval.ee
cache:
  packages: true
  directories:
  - $HOME/bin
before_install:
- sudo apt-get update -q
- sudo apt-get install libimage-exiftool-perl -y
before_script:
- Rscript -e 'blogdown::install_hugo()'
script:
- Rscript -e 'blogdown::build_site()'
before_deploy:
- openssl aes-256-cbc -K $encrypted_288f77d8e810_key -iv $encrypted_288f77d8e810_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- chmod +x ./deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: XEN7e4mr4bYCISLJEWFdG+9F2AdcgiVp/jKNLeV7dOpbR8H+i3+B6nNYy2zLc+LGa0bfZxdl9CqoB6D+upOCBvdKMb08kO4QqTFRCcYd+i63GdWiaRcXyZxLtQ7E4Nu4j8Msd4P1jiInDmUK0Ry0X9T89sCavuzg3uRMawBEcF7R/7XRpXHlb9jUlVGoZ1LjuF13EO9sG3s2stj4xkrDhqOcXh2dJnodNeIEkxEkKewA+G8osfB23LlyVG1wqzd5Vo86hXURySH6E+sgGhwGlP58C5A/WSpUtjasiwUuhNOCW7hU4jxfmPThcfpDDwshjGmTkhFVd0zzZSH/aZwZXflOPa4ocicjEXmaWBwE5Rbx2k70xj4oQB2TcXrwSQqqibT16AR6tc1NROX1QhCzaYC3a53v0BtfvmpTdiZfyYfizqDvQeKIh6ZtkftjVbfsHuUqjAeftB8Zi6N5YWbz4K7ep/7RjQlyMUy/r56S7rI1zBgmnloIy3DtjGS1BsqC+gSz6+BZSRzGW8V+lb7BRYCMYFonliMVfXoAL1+eUyOLsfaQ5UgmY/lYTQ9S8lMCIUwEta0L6Rjrun1LgN+HVsoKBUjveHcnwwEgmQ24u5E5PJaTB/74Y2lLdggQfnJjBcXHTRNHX3ecP8Hxcn5MXbfAhMPxtMDJL1rwGqIBxA4=
  - secure: mXps3YiUFmwOHn/1NWUct2vE+536XxnRRONz0sAuNCSXSnJnaIYmqvHZQzjcyrRQ3Uj5c0p2BaeDrcUhO6iAX9sCrVmbYfvlGWjLzc7EOEpxf0TII6LtgaY/N1+katRznzttWP2LBIwFEbaPZ0oqMXhWqVcoZU6pPYdL+W0rZcY8mVl7cw3XeAjYiZlla8mvFjxuxAGGlmLpa0WPiIj8awLmP3p+B7Z60WsEG7fZhYBKWFyeqnml1YjQdd2REdgQLyABRL1fAYHvJpzXlf9+FVFq735tFzbnLxFrinuYxMwU5aolHma1kO1uoM9FRTYWDi3giFpr9nMTTGwKHnqfyqd8jO6JFPcE2gA4T7tfneO4ux775poAezum6n8tWzUK2y1oF9LfMKjGlzRWBlVdOVnoZVX71RPGvaEy0P+VoAy9QsRirhtWFHHYLTVzei56s7gK4yM8lWbzSXLh/OMbiF0Dm5m15qRcyeeiTIFvYmywCtgHSI3aNvAi/ClfYFdrpPVYJVgbnjPOfFmNm5XvHiZknZjxBhk6t2fIOZ9DEX3+Mae0XiZrBBXvnJ0u4iWNqSo2+EKax5DeAg1/vXxBSm8HMP95um/Q4o/MmL2QlMPrnHoz7awfsPY0VJuUpX6mNEdUvmIcmdetSR4iEzmzrltqazj86dXyNyX6x5k9eSo=
  - secure: QjPW3f4utr1Yus1QFBv58czw2cV5+ApcjtnKzFj/Qs1f9lvPc2oqUwbzyjPAiUnxQZ1/cN7Qa4VLmcYaRNJpoJCQZ3oVIkax4cMRLwIt/zqiydpBpUFroS30dWstTfYmiykMlt76RkzLZbm1isx+YuqoZraQesxvYmJa9Lw7RL9zUoggfzWA/ecYM380NDSjaCNFGDazyByT/1C6E+/L6nF0NBjfky8DJwDqO62AkOkwuMW8by0U8eIj7AhVOj28KuPD24N3u2Wpuk7HkZhSJ2VMyVczevxmXrTHnirfephHUzfq5yT+vSaJTJxSLvr9yxn+w6+6LnppBcqgu6Nyo4dU/2XMMbfvjwLo7hcq1DPimYAKHcgkCFa9jfREFH508socAt2EIAnEFQbd8AfgHPxtt/ZRugNikCVbZlGochftFik4E7o8nKRHCRG1qOQtFJnwf0BmY9VPACHpAAmtAiNv6S/El5cYlX86qqFDmzVEOFlgpmooEU9Cp9+wbxryNxsI7+x3opFvJiFbpTs12t096ux0tLTOF3Et03vV175YhrQhARBQqTOKQj5W9UzwAuMpCJRv3OBHbJdF010lqjqpqCoOQTcHBCsLLMwc5LdXregvLCaQgMc0hXt9va+K8s0WbrEdmRCeQd9xPcdXeNzwz+c2nZewVbzeRMOf1xs=
  - secure: cMCfABkHsT6+QxUNAoaeTyJ1U3FPcoOLTnIV0Y6q7dhgJHVNU2QebWf7tcn3cc/DnENOfL1CjfHUiEYJ5ITjR8gEOH5y5LT3mXviegSO21whHzJNjteqoI3h5TD1eYqDjih/2dKoC+gnOAd1PbdceZzi5rWKt14KcsBU6sPESin2sPV/2SN/ivleX5n6bOqjrszxGBG8VkKR7F0e14GlFc8jPddmihfhby/DMH2dMf8OXYGcZKGYvclweEsYQoeS8Zn8ewmo/W/Wgs0wW//myK7tTt+XWEW3UQahMkKB+jHGsEAh4C1Ee53fnRgfDWmFxIK8jNDAc2pTFC19PyoOWCXl3iwuEPl9XIYXBnUHt4nYdi3Gxpp9+qLTg67udfyvWIXWOoepFxqLXn+9i1p1qyd8+sK9OfQrFOrZsEQ16MKEtVXTpD3Dgz87lsQsxe0OejP+x6pOYmM38a8N3nkVyaYon1eHiReH3HduyK9/VhAX8eIrDG4XwkKXO/00A65FyUnMMVvBDgtUAnMtLtNKYNQRKgoF7wFP72Qw12Bes6/vlK2BVrOctV/70Z4p+bkxGpNqlOPuTwIsXbk/17/kuMDErWxsNrspkhuVN5AxZyZ12c+c2EqiJ7DOSHhgedEa0+iD5Mhdu+Gz97F08cnOy8335men2M6WeJTiXaSUlmA=
