language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libimage-exiftool-perl -y

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"
  - chmod +x ./deploy.sh
  - echo -e "Host *\n\tStrictHostKeyChecking no\nUserKnownHostsFile /dev/null\nLogLevel ERROR\n" >> ~/.ssh/config

script:
  - "Rscript -e 'blogdown::build_site()'"

addons:
  - ssh_known_hosts: virt64551@credibleinterval.ee

before_deploy:
  - openssl aes-256-cbc -K $encrypted_288f77d8e810_key -iv $encrypted_288f77d8e810_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
