# Site settings
baseurl = "https://band-master-allen-43050.netlify.com"
languageCode = "en-us"
title = "Credibleinterval"
theme = "hugo-agency-theme"
relativeURLs = true
canonifyURLs = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-100332037-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Taavi Päll"
  description = "statistika, visualiseerimine, graafik, R, raport, rmarkdown, knitr, excel, csv, Bayes"
  dateformat = "02 Jan 2006"
  disqus = "www-credibleinterval-ee"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Lehte ei leitud"
    text = "Palun mine [siia](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Credibleinterval"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
    services = "Teenused"
    portfolio = "Portfolio"
    about = "Info"
    team = "Meeskond"
    contact = "Kontakt"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10
    
    [[menu.postpend]]
     url = "https://blog.credibleinterval.ee"
     name = "R Blog"
     weight = 10
     
     [[menu.postpend]]
      name = "Galerii"
      weight = 10
      identifier = "post"
      url = "/post/"
     
  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Tere tulemast Credibleinterval lehele!"
    subtitle = "Andmed, graafikud, statistiline analüüs"
    buttonText = "Siit saad abi"


  # Services section
  [params.services]
    enable = true
    title = "Teenused"
    subtitle = "Andmetöötlus, statistiline analüüs, visualiseerimine, raportid."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-table"
      title = "Andmetöötlus"
      description = "Andmete ettevalmistamine analüüsiks -- import erinevatest tabelformaatidest, andmebaasidest ja web API-dest. Andmete puhastamine ja transformeerimine sobivale kujule."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-bar-chart"
      title = "Visualiseerimine"
      description = "Lihtsate kuni kõrgelt multidimensionaalsete andmete visualiseerimine. Publikatioonivalmis graafikud. Hea visualisatsioon näitab sulle asju mida sa ei ole oodanud ja tõstatab uusi küsimusi."
      url = "/tags/visualiseerimine"

    [[params.services.row.list]]
      icon = "fa-balance-scale"
      title = "Statistika"
      description = "Andmete mudeldamine, statistiline analüüs. Mudelid komplementeerivad visualisatsioone ja aitavad vastata andmete põhjal tekkinud küsimustele."
      #url = "#"

[[params.services.row.list]]
      icon = "fa-file-word-o"
      title = "Raportid"
      description = "Tulemuste vormistamine efektiivseks kommunikeerimiseks. Raportid html, pdf või doc formaadis."
      url = "/tags/raportid"


  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfell"
    subtitle = "Näited erinevatest võimalustest."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = false
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2009-2011"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "2.jpg"
      date = "March 2011"
      title = "An Agency is Born"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "December 2012"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "July 2014"
      title = "Phase Two Expansion"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Meeskond"
    subtitle = ""
    description = "Taavil on doktorikraad geenitehnoloogia erialal ja pikaajaline laboratoorse uurimistöö kogemus molekulaarse biomeditsiini vallas. Taavi õpetab [R statistika programmi kasutamist andmeanalüüsis](https://tpall.github.io/learn-r/) Tartu Ülikoolis doktorikooli raames ja [Onkobioloogia](https://onkobioloogia.netlify.com) loengut Tallinna Tehnikaülikoolis Keemia- ja biotehnoloogia instituudis."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "tp-icon.png"
      name = "Taavi Päll, PhD"
      position = "asutaja, Magrittr oü"
      #reportsTo = ""
      livesIn = "[Tallinnas](https://www.google.ee/maps/@59.3974763,24.6595288,17z?hl=en)"
      #scope = [
      #  "UX for [member dashboard](#)",
      #  "Maintainer for [awesome-project](#)",
      #  "Open Source [community management](#)"
      #]
      # For bio markdown and even multiline strings are available.
      bio = "Taavi osutab abi andmete esitamisel ja statistilisel analüüsil. Hea meelega aitab ja konsulteerib probleemide korral [__R__](https://cran.rstudio.com) statistilise analüüsi programmiga. Kokkuleppel [__R__](https://cran.rstudio.com), [__RStudio__](https://www.rstudio.com) ja [__rmarkdowni__](http://rmarkdown.rstudio.com) lühikursus."
      social = [
        ["fa-twitter", "https://twitter.com/taavipall"],
        ["fa-github", "https://github.com/tpall"],
        ["fa-linkedin", "https://www.linkedin.com/in/palltaavi/"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Võta ühendust"
    #subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Saada"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "taavi.pall@credibleinterval.ee"

    # Success and error message overwrite for async contact form
    #thanks = "Suured tänud! Sinu kiri on saadetud."
    #error = "Kirja ei olnud võimalik saata. Palun kontakteeru kasutades palltaavi@gmail.com aadressi."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Sinu nimi *"
      warning = "Palun sisesta oma nimi."

    [params.contact.form.email]
      text = "Sinu e-post *"
      warning = "Palun sisesta oma E-posti aadress."

    [params.contact.form.phone]
      text = "Sinu telefon *"
      warning = "Palun sisesta oma telefoni number."

    [params.contact.form.message]
      text = "Sinu sõnum *"
      warning = "Palun sisesta sõnum."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

# Footer section
  [params.footer]
    enable = true
    #copyright = "Published under the Apache License 2.0."

  [[params.footer.contact]]
      text = "Magrittr OÜ<br>Reg. nr. 12856143<br>SEB Pank a/a: EE511010220244448227<br>SWIFT: EEUHEE2X<br>Veebileht on arenduses!"
  
